import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#9bf6ba',
        'error-container': '#ffdad6',
        primary: '#006036',
        'tertiary-fixed': '#ffdada',
        'on-error': '#ffffff',
        'surface-container': '#edeeeb',
        'inverse-surface': '#2e312f',
        'outline-variant': '#bec9be',
        'tertiary-container': '#a94e56',
        'inverse-primary': '#80d9a0',
        'secondary-fixed-dim': '#ffb955',
        'surface-bright': '#f9faf7',
        'on-primary-container': '#abffc6',
        'on-surface-variant': '#3f4941',
        background: '#f9faf7',
        'secondary-fixed': '#ffddb4',
        'on-secondary': '#ffffff',
        outline: '#6f7a70',
        'on-secondary-container': '#6b4500',
        'on-primary-fixed-variant': '#00522e',
        'surface-container-high': '#e7e8e6',
        'surface-container-low': '#f3f4f1',
        'surface-variant': '#e2e3e0',
        tertiary: '#8b373f',
        'on-secondary-fixed': '#291800',
        'on-tertiary-fixed': '#40000d',
        secondary: '#835500',
        'primary-container': '#1a7a4a',
        'on-primary-fixed': '#00210f',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-surface': '#191c1b',
        'tertiary-fixed-dim': '#ffb3b6',
        'surface-dim': '#d9dad8',
        'inverse-on-surface': '#f0f1ee',
        'surface-container-highest': '#e2e3e0',
        'secondary-container': '#feae2c',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f9faf7',
        'surface-tint': '#006d3f',
        'primary-fixed-dim': '#80d9a0',
        'on-secondary-fixed-variant': '#633f00',
        'on-tertiary-fixed-variant': '#7c2b34',
        'on-background': '#191c1b',
        'on-tertiary-container': '#ffe7e7',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        sm: '0.5rem',
        md: '1rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        diffusion: '0 12px 32px rgba(25, 28, 27, 0.04)',
        'diffusion-md': '0 12px 32px rgba(25, 28, 27, 0.08)',
      },
    },
  },
  plugins: [],
}

export default config
